services:
  db:
    image: postgres:17.2-alpine
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dailynews_production
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dailynews_production"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rails_network

  rails:
    image: ghcr.io/oddsteam/dailynews-e-newspaper:latest
    platform: linux/amd64
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - APP_ENV=uat
      - SCRIPT_NAME=/e-newspaper
      - SOLID_QUEUE_IN_PUMA=true
    networks:
      - rails_network
      - kamal

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - rails
    networks:
      - rails_network
      - kamal
    restart: always

networks:
  rails_network:
  kamal:
    external: true

volumes:
  postgres:
  bundle: