services:
  db:
    image: postgres:17.2-alpine
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dailynews_production"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rails_network

  rails:
    image: ghcr.io/oddsteam/dailynews-e-newspaper:latest
    platform: linux/amd64
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - HUAWEICLOUD_ACCESS_KEY_ID=${HUAWEICLOUD_ACCESS_KEY_ID}
      - HUAWEICLOUD_SECRET_ACCESS_KEY=${HUAWEICLOUD_SECRET_ACCESS_KEY}
      - HUAWEICLOUD_BUCKET=${HUAWEICLOUD_BUCKET}
      - HUAWEICLOUD_REGION=${HUAWEICLOUD_REGION}
    networks:
      - rails_network
      - kamal

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - rails
    networks:
      - rails_network
      - kamal
    restart: always

networks:
  rails_network:
  kamal:
    external: true

volumes:
  postgres:
  bundle: